CLASS zcl_lab_68_package_b DEFINITION INHERITING FROM zcl_lab_66_travel
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_68_package_b IMPLEMENTATION.
ENDCLASS.
