CLASS zcl_lab_67_package_a DEFINITION INHERITING FROM zcl_lab_66_travel
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_67_package_a IMPLEMENTATION.
ENDCLASS.
