CLASS zcl_lab_66_travel DEFINITION ABSTRACT
  PUBLIC

  CREATE PUBLIC .

  PUBLIC SECTION.
   METHODS transport_oneway ABSTRACT IMPORTING iv_transport_oneway TYPE REF TO IF_OO_ADT_CLASSRUN_OUT.
   METHODS day_one          ABSTRACT IMPORTING iv_day_one          TYPE REF TO IF_OO_ADT_CLASSRUN_OUT.
   METHODS day_two          ABSTRACT IMPORTING iv_day_two          TYPE REF TO IF_OO_ADT_CLASSRUN_OUT.
   METHODS day_three        ABSTRACT IMPORTING iv_day_three        TYPE REF TO IF_OO_ADT_CLASSRUN_OUT.
   METHODS transport_return ABSTRACT IMPORTING iv_transport_return TYPE REF TO IF_OO_ADT_CLASSRUN_OUT.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_66_travel IMPLEMENTATION.




ENDCLASS.
